CHARITY = {
    "category": 
    {
        "education": [
            {"name": "Boys & Girls Clubs of America",
             "img": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Bgcalogo.svg/1280px-Bgcalogo.svg.png",
             "url": "http://www.bgca.org/Pages/index.aspx",
             "summary": "Inspiring and enabling all young people to realize their full potential as productive, responsible, and caring citizens."},
            {"name": "Compassion International",
             "img": "https://2f6f9f21c655dcba80f4-5bdaf0a086c14c5ecb76e1191595be4d.ssl.cf1.rackcdn.com/logos/English_logo_2_color_with_tag_line.jpg",
             "url": "https://www.compassion.com/",
             "summary": "Compassion International is a Christian humanitarian aid child sponsorship organization dedicated to the long-term development of children living in poverty around the world. "},
            {"name": "Smithsonian Institution",
             "img": "https://lh5.googleusercontent.com/-VOCH758a0eA/AAAAAAAAAAI/AAAAAAAABYc/rTbAQJazRGo/s0-c-k-no-ns/photo.jpg",
             "url": "https://www.si.edu/",
             "summary": "The Smithsonian Institution, established in 1846 'for the increase and diffusion of knowledge', is a group of museums and research centers administered by the Government of the United States."},
            {"name": "Teach for America",
             "img": "https://lh3.googleusercontent.com/-oLOpx0fWtIA/AAAAAAAAAAI/AAAAAAAAEvc/p1Vk4mCCR-c/s0-c-k-no-ns/photo.jpg",
             "url": "https://www.teachforamerica.org/",
             "summary": "Teach For America is a nonprofit organization whose stated mission is to 'enlist, develop, and mobilize as many as possible of our nation's most promising future leaders to grow and strengthen the movement for educational equity and excellence.'"},
            {"name": "Scholarship America",
             "img": "https://scholarshipamerica.org/wp-content/uploads/2016/06/scholarship-america-retina-logo-2016.png",
             "url": "https://scholarshipamerica.org/",
             "summary": "Scholarship America was founded in 1958, on the revolutionary idea that community support of scholarships could bring college education within reach for millions of students who couldn't otherwise afford it."}
        ],
        "healthcare": [
            {"name": "American National Red Cross",
             "img": "http://www.phillyveteransparade.org/wp-content/uploads/2016/09/American-Red-Cross.jpg",
             "url": "www.redcross.org/",
             "summary": "American National Red Cross, is a humanitarian organization that provides emergency assistance, disaster relief and education in the United States" },
            {"name": "Mercy Medical Angels",
             "img": "http://mercymedical.org/mission_parser/assets/images/Mercy-Medical-Angels-side.jpg",
             "url": "mercymedical.org/",
             "summary": "MMA bridges the access gap by providing charitable medical transportation throughout the United States and at times internationally." },
            {"name": "Task Force for Global Health",
             "img": "https://www.taskforce.org/wp-content/uploads/2016/08/TFGH_blue.png?x71580",
             "url": "https://www.taskforce.org/",
             "summary": "The Task Force consists of eight programs and five projects focused on neglected tropical diseases, vaccine-preventable diseases, and health systems strengthening."},
            {"name": "YMCA (The Young Men's Christian Association)",
             "img": "http://www.lessingflynn.com/media/cms/YMCA-logo.gif",
             "url": "http://www.ymca.int/",
             "summary": "The Y is a cause-driven organization that is for youth development, for healthy living and for social responsibility."},
            {"name": "St. Jude's Child Research Hospital",
             "img": "https://www.stjude.org/get-involved/find-an-event/dinners-and-galas/tomorrownite-gala-benefiting-st-jude-children-s-research-hospital/_jcr_content/image.img.800.high.png/1478641849643.png",
             "url": "https://www.stjude.org/",
             "summary": "St. Jude Children's Research Hospital, founded in 1962, is a pediatric treatment and research facility focused on children's catastrophic diseases." },
             ],
        "climate": [
            {"name": "Habitat for Humanity",
             "img": "http://www.experian.com/assets/marketing-services/images/habitat-for-humanity1.gif",
             "url": "www.habitat.org/node/1",
             "summary": "Habitat has been devoted to building 'simple, decent, and affordable' housing, and has addressed the issues of poverty housing all over the world."},
            {"name": "The Nature Conservancy",
             "img": "https://pbs.twimg.com/profile_images/608258767092908033/njR5TGTo.png",
             "url": "www.nature.org/",
             "summary": "The Nature Conservancy is a charitable environmental organization to 'conserve the lands and waters on which all life depends.'"},
            {"name": "World Wildlife Fund",
             "img": "https://lh5.googleusercontent.com/--j3d6NXYwD0/AAAAAAAAAAI/AAAAAAAAEHU/8u0WmyUdc_s/s0-c-k-no-ns/photo.jpg",
             "url": "www.worldwildlife.org/",
             "summary": "The World Wide Fund for Nature is an international non-governmental organization founded in 1961, working in the field of the wilderness preservation, and the reduction of humanity's footprint on the environment." },
            {"name": "Foothill Land Conservancy",
             "img": "http://foothillsland.org/wp-content/themes/FLC/img/logo.png",
             "url": "foothillsland.org/",
             "summary": "The Foothills Land Conservancy is a non-profit organization whose purpose and mission are the protection and preservation of conservation values of natural and productive landscapes in the foothills of the Great Smoky Mountains and their surroundings."},
              ],
        "economy": [
            {"name": "United Way Worldwide",
             "img": "https://lh4.googleusercontent.com/-ydbERTHC0j4/AAAAAAAAAAI/AAAAAAAAAw8/2kACVMwFmFA/s0-c-k-no-ns/photo.jpg",
             "url": "https://www.unitedway.org/",
             "summary": "United Way Worldwide is the leadership and support organization for the network of nearly 1,800 community-based United Ways in 45 countries and territories."},
            {"name": "Feeding America",
             "img": "https://lh3.googleusercontent.com/-i7Mqtn1dlUY/AAAAAAAAAAI/AAAAAAAAAy4/4tzJbbCyiD4/s0-c-k-no-ns/photo.jpg",
             "url": "www.feedingamerica.org/",
             "summary": "Feeding America is a United States-based nonprofit organization that is a nationwide network of more than 200 food banks that feed more than 46 million people through food pantries, soup kitchens, shelters, and other community-based agencies. "},
            {"name": "The Salvation Army",
             "img": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/The_Salvation_Army.svg/868px-The_Salvation_Army.svg.png",
             "url": "www.salvationarmyusa.org/",
             "summary": "The Salvation Army is a Christian Protestant church and international charitable organization structured in a quasi-military fashion."},
            {"name": "Food For the Poor",
             "img": "https://lh3.googleusercontent.com/-tVltgM6y_vY/AAAAAAAAAAI/AAAAAAAAALQ/ITXit_cSQrY/s0-c-k-no-ns/photo.jpg",
             "url": "www.foodforthepoor.org/",
             "summary": "Food For The Poor, Inc. is an ecumenical Christian nonprofit organization that provides food, medicine, and shelter, among other services, to the poor in Latin America and the Caribbean."},
            {"name": "Goodwill Industries International, Inc.",
             "img": "https://lh6.googleusercontent.com/-eamjlm8uGpM/AAAAAAAAAAI/AAAAAAAAAOU/GqLsOYz_ivs/s0-c-k-no-ns/photo.jpg",
             "url": "www.goodwill.org/",
             "summary": "Goodwill Industries International Inc. is an American nonprofit organization that provides job training, employment placement services, and other community-based programs for people who have barriers preventing them from otherwise obtaining a job."},
              ],
        "immigration": [
            {"name": "Greater Pittsburgh Literacy Council",
             "img": "https://www.gplc.org/images/logo-gplc-home.gif",
             "url": "https://www.gplc.org/",
             "summary": "Nonprofit agency providing literacy programs for adults and out-of-school young adults in western Pennsylvania."},
            {"name": "American Immigration Council",
             "img": "https://m1.fluidreview.com/media/assets/reviewrooms/aic-j1program/logo/ImmCouncil_color_notag.jpg",
             "url": "https://americanimmigrationcouncil.org/",
             "summary": "The American Immigration Council (“Council”), established in 1987, works to strengthen America by honoring our immigrant history and shaping how America thinks about and acts towards immigrants and immigration." },
            {"name": "Upwardly Global",
             "img": "https://www.upwardlyglobal.org/++theme++upg.theme/images/site-logo.png",
             "url": "https://www.upwardlyglobal.org/",
             "summary": "Upwardly Global is a 501c3 non-profit organization organization that helps immigrant, refugee and asylee professionals rebuild their careers in the United States. "},
            {"name": "Border Angels",
             "img": "http://www.borderangels.org/wp-content/uploads/2016/04/BALOGOBLACKTRANS.png",
             "url": "www.borderangels.org/",
             "summary": "Border Angels is an all volunteer, non profit organisation that advocates for human rights, humane immigration reform, and social justice with a special focus on issues related to issues related to the US-Mexican border. "},
            {"name": "Coalition for Humane Immigrant Rights of Los Angeles (CHIRLA)",
             "img": "http://www.chirla.org/sites/default/files/CHIRLALogoWEB.png",
             "url": "www.chirla.org/",
             "summary": "CHIRLA is a California-based, immigrant rights, civil rights, and human rights organization with national impact. "}],
    }

}